---
env:
  global:
    - ANSIBLE_FORCE_COLOR=true ANSIBLE_STDOUT_CALLBACK=yaml ANSIBLE_COLOR_CHANGED=yellow
dist: xenial
sudo: required

addons:
  apt:
    packages:
      - expect-dev # for unbuffer

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - git clone -b ${lint_version} https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip install --upgrade ansible==2.5.* ansible-lint docker-py molecule==2.17 pyOpenSSL PyYAML
  - ansible --version

script:
  - unbuffer ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  - unbuffer molecule test -s default

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
