---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    collections-path: ~/.ansible/collections
driver:
  name: ec2
lint: ansible-lint
platforms:
  - name: test-aws-centos7-mysql-5.6
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.05
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

  - name: test-aws-Debian9-mysql-5.6
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.05
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - pip3

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      pip3:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
    prepare: ../resources/prepare.yml
scenario:
  name: cloud-aws-direct-5.6
verifier:
  name: ansible
