---
- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  register: mysql_config
  notify: restart mysql

- name: Verify mysql pid directory exists.
  file:
    path: "{{ mysql_pid_file | dirname }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755

- name: Clean InnoDB logs
  block:
    - name: Stop MySQL to change configs
      service:
        name: '{{ mysql_service_name }}'
        state: stopped

    - name: Find InnoDB log files
      find:
        paths: '{{ mysql_datadir }}'
        patterns: 'ib_logfile*'
      register: innodb_log

    - name: Remove default InnoDB log files
      file:
        path: '{{ idb_log.path }}'
        state: absent
      loop: '{{ innodb_log.files }}'
      loop_control:
        loop_var: idb_log
  when: mysql_config.changed | bool

- name: Verify mysql include directory exists.
  file:
    path: "{{ mysql_config_include_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: mysql_config_include_files | length

- name: Create slow query log file (if configured).
  file:
    path: "{{ mysql_slow_query_log_file }}"
    state: touch
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: 0640
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"
  when: mysql_slow_query_log_enabled

- name: Create errorlog file (if configured).
  file:
    path: "{{ mysql_log_error }}"
    state: touch
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: 0640
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"
  when: mysql_log_error != ""

- name: Ensure MySQL is started.
  service:
    name: '{{ mysql_service_name }}'
    state: started
    enabled: True

- name: Wait for service to be ready
  wait_for:
    port: '{{ mysql_port }}'
    host: '{{ mysql_bind_address }}'
    connect_timeout: 3
    delay: 3
    timeout: 30
