---
- name: "Add repository and install {{ mysql_version }} packages"
  block:
    - name: 'Install requirements'
      apt:
        name: '{{ mysql_python_packages }}'
        state: present
      register: task_result
      retries: 10
      delay: 2
      until: task_result is succeeded

    # - name: 'Add Mysql apt key'
    #   apt_key:
    #     keyserver: pgp.mit.edu
    #     id: 5072E1F5
    #     state: present
    #   register: apt_key_install
    #   retries: 10
    #   delay: 2
    #   until: apt_key_install is succeeded

    # - name: 'Copy mysql.list'
    #   template:
    #     src: mysql.list.j2
    #     dest: /etc/apt/sources.list.d/mysql.list
    #     owner: root
    #     group: root
    #     mode: 0644

    - name: 'apt-get update'
      apt:
        update_cache: yes
      changed_when: false
      register: task_result
      retries: 10
      delay: 2
      until: task_result is succeeded

    - name: 'Install {{ mysql_daemon }}'
      apt:
        name: '{{ mysql_packages }}'
        state: present
        update_cache: yes
      register: task_result
      retries: 10
      delay: 2
      until: task_result is succeeded

  become: True
