---
- name: Add repository and install {{ mysql_version }} packages
  block:
    - name: Add universe repository for Ubuntu
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install requirements
      apt:
        name: '{{ mysql_python_packages }}'
        state: present
      register: task_result
      until: task_result is succeeded

    - name: Add Mysql apt key
      apt_key:
        keyserver: '{{ mysql_apt_keyserver }}'
        id: '{{ mysql_apt_key_id }}'
        state: present
      register: apt_key_install
      until: apt_key_install is succeeded

    - name: Copy mysql.list
      template:
        src: '{{ mysql_apt_template }}.j2'
        dest: /etc/apt/sources.list.d/mysql.list
        owner: root
        group: root
        mode: 0644
  become: true
