---
- name: "Add repository and install {{ mysql_version }} packages"
  block:
    - name: "Ensure Python libraries are installed."
      apt:
        name: "{{ mysql_python_packages }}"
        state: present
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2

    - name: "Get MySql apt repository"
      get_url:
        url: "{{ mysql_repo }}"
        dest: /tmp/mysql-apt-config_0.8.12-1_all.deb
      when: mysql_daemon != "mariadb"

    - name: "Installing deb package"
      apt:
        deb: /tmp/mysql-apt-config_0.8.12-1_all.deb
        state: present
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
      when: mysql_daemon != "mariadb"

    - name: "Selecting version {{ mysql_version }}"
      debconf:
        name: mysql-apt-config
        question: mysql-apt-config/select-server
        value: "mysql-{{ mysql_version }}"
        vtype: select
      when: mysql_daemon != "mariadb"

    - name: "Reconfiguring package"
      command: dpkg-reconfigure mysql-apt-config
      environment:
        DEBIAN_FRONTEND: noninteractive
      changed_when: false
      when: mysql_daemon != "mariadb"

    - name: "Running apt-get update"
      apt:
        update_cache: yes
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2

    - name: "Installing database"
      apt:
        name: "{{ mysql_packages }}"
        state: present
        update_cache: yes
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2

  become: True
