---
- name: Add repository and install {{ mysql_version }} packages
  block:
    - name: Add universe repository for Ubuntu
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install requirements
      apt:
        name: '{{ mysql_python_packages }}'
        state: present
      register: task_result
      until: task_result is succeeded

    - block:
        - name: Add Mysql apt key
          apt_key:
            keyserver: pgp.mit.edu
            id: 5072E1F5
            state: present
          register: apt_key_install
          until: apt_key_install is succeeded

        - name: Copy mysql.list
          template:
            src: mysql.list.j2
            dest: /etc/apt/sources.list.d/mysql.list
            owner: root
            group: root
            mode: 0644
      when: mysql_daemon == 'mysqld'

    - name: Install {{ mysql_daemon }} {{ mysql_version }}
      apt:
        name: '{{ mysql_packages }}'
        state: present
        update_cache: true
      register: task_result
      retries: 3
      delay: 2
      until: task_result is succeeded

    - name: Install pip requirements
      pip:
        name:
          - mysql-connector-python
          - PyMySQL
        state: present
      register: mysql_connector_install
      until: mysql_connector_install is succeeded

  become: true
