---
- name: Prepare python3
  hosts: rhel7
  become: true
  vars:
    ansible_python_interpreter: auto
  tasks:

    - name: Add repository
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
        update_cache: true
      register: task_result
      until: task_result is succeeded

    - name: Install python3
      yum:
        name:
          - python36
          - python-dnf
        state: present
        update_cache: true
      register: task_result
      until: task_result is succeeded
