---
- name: Prepare python3
  hosts: rhel7
  become: true
  vars:
    ansible_python_interpreter: auto
  tasks:

    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
        gpgcheck: false

    - name: Install python3
      yum:
        name:
          - python36
          - python3-pip
          - python-dnf
        state: present
        update_cache: true
      register: task_result
      until: task_result is succeeded
