---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-mysql-5.5
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/provisioning/AWS/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-direct-5.5
verifier:
  name: ansible
  lint:
    name: ansible-lint
