---
- name: restart mysql
  service:
    name: '{{ mysql_daemon }}'
    state: restarted
    sleep: 5

- name: result root password change
  file:
    path: /tmp/temporary_password_changed.txt
    state: touch
