---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-mysql-8.0
    image: ami-0f9cf087c1f27d9b1# ubuntu
#    image: ami-9887c6e7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-01be2149
    spot_price: 0.05
    wait_timeout: 1800
    ssh_user: root
    security_group_name:
      - default
      - epmldi-docker-machine
    groups:
      - debian_family
#  - name: test-aws-centos6-mysql-5.7
#    image: ami-1585c46a
#    instance_type: m4.large
#    region: us-east-1
#    vpc_subnet_id: subnet-01be2149
#    spot_price: 0.04
#   wait_timeout: 1800
#    ssh_user: centos
#    groups:
#      - rhel_family
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/provisioning/AWS/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-aws-direct-8.0
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
