---
- name: Converge
  hosts: centos7
  become: true
  tasks:

    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        # baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
        gpgcheck: false

    - name: Install python3
      yum:
        name:
          - python36
          - python3-pip
        state: present
        update_cache: true
      register: task_result
      until: task_result is succeeded