---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-mysql
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
provisioner:
  name: ansible
  # log: True
  # env:
  #   ANSIBLE_FORCE_COLOR: True
config_options:
  defaults:
    stdout_callback: yaml
    bin_ansible_callbacks: True
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
