---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-mysql
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
  # - name: test-docker-centos6-mysql
  #   image: leandelivery/docker-systemd:centos6
  #   privileged: True
  #   groups:
  #     - rhel_family
provisioner:
  name: ansible
options:
  config_options:
    defaults:
      stdout_callback: debug
      bin_ansible_callbacks: True
  # log: True
  lint:
    name: ansible-lint
    options:
      force-color: True
      'c': .ansible-lint
      'r': ~/ansible-lint-rules/rules/
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
