---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: ansible-lint
platforms:
  - name: test-docker-centos7-mysql
    image: leandelivery/docker-systemd:centos7
    privileged: true
    groups:
      - rhel_family
      - centos7

  - name: test-docker-ubuntu1804-mysql
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family

provisioner:
  name: ansible
  log: false
  inventory:
    group_vars:
      pip3:
        ansible_python_interpreter: /usr/bin/python3
      pip2:
        mysql_python_packages:
          - gcc
          - python36
          - python3-pip
          - perl-DBD-MySQL
          - python3-devel
          - mysql-devel
  playbooks:
    verify: ../resources/tests/verify.yml
    prepare: ../resources/prepare.yml
scenario:
  name: default
verifier:
  name: ansible
