---
dependency:
  name: {{ cookiecutter.dependency_name }}
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: {{ cookiecutter.lint_name }}
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-{{ cookiecutter.role_name }}
    image: CentOS7_64-bit
    shape: small
    region: AWS-EUCENTRAL
    wait_timeout: 1800
    groups:
      - rhel_family
  - name: test-aws-ubuntu1804-{{ cookiecutter.role_name }}
    image: Ubuntu18.04_64-bit
    shape: small
    region: AWS-EUCENTRAL
    wait_timeout: 1800
    groups:
      - debian_family
provisioner:
  name: ansible
  # log: True
  playbooks:
    create: ../resources/provisioning/create.yml
    prepare: ../resources/provisioning/prepare.yml
    destroy: ../resources/provisioning/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: {{ cookiecutter.provisioner_lint_name }}
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-aws-delegated
verifier:
  name: {{ cookiecutter.verifier_name }}
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: {{ cookiecutter.verifier_lint_name }}
