---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    collections-path: ~/.ansible/collections
driver:
  name: ec2
lint: ansible-lint
platforms:
  - name: test-aws-centos7-mysql-5.7.31
    platform: centos7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.05
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - rhel7

  - name: test-aws-ubuntu18-mysql-5.7
    platform: ubuntu18
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    security_group_name:
      - default
    spot_price: 0.05
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - minor_ubuntu

  - name: test-aws-Debian9-mysql-5.7
    platform: debian9
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.05
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - pip3

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      pip3:
        ansible_python_interpreter: /usr/bin/python3
      minor_ubuntu:
        ansible_python_interpreter: /usr/bin/python3
        mysql_artifacts:
          - https://downloads.mysql.com/archives/get/p/23/file/mysql-community-client_5.7.31-1ubuntu18.04_amd64.deb
          - https://downloads.mysql.com/archives/get/p/23/file/mysql-client_5.7.31-1ubuntu18.04_amd64.deb
          - https://downloads.mysql.com/archives/get/p/23/file/mysql-community-server_5.7.31-1ubuntu18.04_amd64.deb
          - https://downloads.mysql.com/archives/get/p/23/file/mysql-server_5.7.31-1ubuntu18.04_amd64.deb
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
    prepare: ../resources/prepare.yml
scenario:
  name: cloud-aws-direct-5.7
verifier:
  name: ansible
