---
- name: Prepare python3
  hosts: minor
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
        update_cache: true
      register: task_result
      until: task_result is succeeded

    - name: Add repository
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Install python3
      apt:
        name:
          - python3.7
          - python3-pip
        state: present
        update_cache: true
      register: task_result
      until: task_result is succeeded
