---
- name: Prepare python3
  hosts: minor
  become: true
  vars:
    ansible_python_interpreter: auto
  tasks:

    - name: Remove python3
      raw: apt-get -y update && apt -y remove python3.5 python3-apt && apt-get -y install software-properties-common

    - name: Install python3.7
      raw: add-apt-repository -y ppa:deadsnakes/ppa && apt-get -y update && apt-get -y install python3.7

    - name: Re-Install python3-apt
      raw: apt-get -y install python3-apt

    - name: Get apt
      shell: ls -la /usr/lib/python3/dist-packages/apt_pkg.cpython*
      register: cmd_res

    - name: debug cmd_res
      debug:
        var: cmd_res
