---
- name: Prepare python3
  hosts: minor
  become: true
  vars:
    ansible_python_interpreter: auto
  tasks:

    - name: Remove python3
      raw: apt-get -y update && update-alternatives --remove-all python3 && apt -y remove python3.5

    - name: Install python3.7
      raw: add-apt-repository -y ppa:deadsnakes/ppa && apt-get -y update && apt-get -y install software-properties-common python3.7

    - name: Update alternatives
      raw: update-alternatives --set python3 /usr/bin/python3.7

    - name: Re-Install python3-apt
      raw: apt-get -y remove python3-apt && apt-get -y install python3-apt
