---
- name: Prepare python3
  hosts: minor
  become: true
  vars:
    ansible_python_interpreter: auto
  tasks:

    - name: Remove python3
      raw: apt-get -y update && apt -y remove python3.5 python3-apt && apt-get -y install software-properties-common

    - name: Install python3.7
      raw: add-apt-repository -y ppa:deadsnakes/ppa && apt-get -y update && apt-get -y install python3.7

    - name: Set apt
      shell: ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-35m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/apt_pkg.so
      register: cmd_res

    - name: debug cmd_res
      debug:
        var: cmd_res

    - name: Set apt
      shell: ls -la /usr/lib/python3.7/dist-packages/apt_pkg.cpython*
      register: cmd_res2

    - name: debug cmd_res2
      debug:
        var: cmd_res2

    - name: Re-Install python3-apt
      pip:
        name: python3-apt
        state: present
        update_cache: true
      register: task_result
      until: task_result is succeeded
