---
- name: Prepare python3
  hosts: minor
  become: true
  vars:
    ansible_python_interpreter: auto
  tasks:

    - name: Remove python3
      raw: "apt-get -y update\
          && apt -y remove --purge python3.5 python-apt python3-apt python-pip python3-pip\
          && rm -rf /usr/local/bin/pip* && rm -rf /usr/local/lib/python3.5\
          && rm -rf /usr/lib/python3\
          && apt-get -y install software-properties-common"

    - name: Install python3.7
      raw: add-apt-repository -y ppa:deadsnakes/ppa && apt-get -y update && apt-get -y install python3.7 python3-setuptools python3-pip python3-apt

    # - name: Set apt
    #   shell: ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-35m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/apt_pkg.so
    #   register: cmd_res

    # - name: debug cmd_res
    #   debug:
    #     var: cmd_res

    # - name: Re-Install python3-apt
    #   pip:
    #     name: python3-apt
    #     state: present
    #   register: task_result
    #   until: task_result is succeeded
