---
- name: Prepare python3
  hosts: minor
  become: true
  vars:
    ansible_python_interpreter: auto
  tasks:

    - name: Re-Install python3
      raw: apt -y remove python3.5 && apt update && add-apt-repository ppa:deadsnakes/ppa && apt install software-properties-common python3.7

    - name: Remove alternatives
      raw: update-alternatives --remove-all python3

    - name: Update alternatives
      alternatives:
        name: python3
        link: /usr/bin/python3
        path: /usr/bin/python3.7

    - name: Re-Install python3-apt
      raw: apt-get -y remove python3-apt && apt-get -y install python3-apt
